---
- name: Update system packages
  hosts: all
  become: yes
  tasks:
    - name: install docker
      apt:
        name: docker.io
        state: latest
    - name: install docker-compose
      apt:
        name: docker-compose
        state: latest
    - name: set user rights for docker
      shell: usermod -aG docker {{ansible_user}}
    - name: restart docker service
      service:
        name: docker
        state: restarted
      